removed some bugs from falling cookies, added others
Catling10/cookieclicker pull request #10
Opened 2022-04-20 06:02 UTC by Catling10

Не знаю, зачем у нас был рандомный айди на ноды, привёл к универсальному увеличивающемуся каунтеру, с этим больше можно сделать, имхо. 
Надо разобраться с таймингами отработки, и по ним добавить ремув нодов с айди -1 от последней операции (написали куки2, убрать куки1, написали куки3, убрать куки2)

2022-04-20 17:24 UTC, segamolder requested changes

2022-04-20 17:24 UTC, segamolder commented on script.js
>          cookie.classList.add("displayNone")
Вот тут, по клику ты можешь удалять ноду, то есть типа
cookie.remove()

2022-04-20 17:24 UTC, segamolder commented on script.js
> +//TODO По каунтеру fallingCounter -1 от последней операции попробовать удалять ноды (попробовал не получилось)
Так как мы не планируем реализовывать кучу падающих печенек разом ты можешь перед тем как создавать новые печеньки (.insertAdjacentHTML), удалить все предыдущие
То есть получить все контейнеры печенек (document.querySelectorAll(".container2")), проверить если .length() > 0, то есть если найдены контейнеры с печеньками, и удалить все:
```
let cookiesContainers = document.querySelectorAll(".container2");
if(cookiesContainers.lenght > 0) {
  cookiesContainers.forEach(cookie => cookie.remove());
}
```
Типа такого, не проверял

2022-04-20 17:24 UTC, segamolder commented on style.css
> +        top: -100px;
Зачем -100px? Похоже на какой-то костыль)

2022-04-20 17:24 UTC, segamolder commented on script.js
> +    fallingCounter++;
Как вариант раз уж ты считаешь количество упавших печенек предлагаю выводить эту информацию, и так же добавить подсчет пойманных печенек
Не забудь сохранять эти данные только)

2022-04-21 02:21 UTC, Catling10 commented on style.css
> +        top: -100px;
Угу. Не понимал, как оно работает, тестил, если вдруг перестанет копиться на самом верху экрана, а будет копиться за 100 пикселей сверху.
Экзактли нерабочий костыль, крч, забыл убрать)

2022-04-21 21:38 UTC, segamolder commented on style.css
> +        top: -100px;
Хорошо, обнови ПР тогда)

2022-04-22 06:00 UTC, merged